### PR TITLE
Add Ertmer's PR template

### LINKED ISSUE #1: Setup Repo/ install dependencies
* Initialize the repo as a React app, and install necessary dependencies such as Jest, and React-Router
* Setup PR Template

### PR DESCRIPTION
**Pull request by GreysonElkins**
#### What's this PR do?
* Adds a template for Pull Requests! 
#### Where should the reviewer start?
Looking at the headers in this PR (suggesting changes or new ones)
#### How should this be manually tested?
Don't write tests for this, that's over kill
#### Any background context you want to provide?
* Aaron and I also set-up some dependencies, which are already on the master. When you pull and run NPM install you'll get `react`, `router`, and `jest` right off the bat. 
* A second repo will either be inbound or need creation tomorrow for the server
#### What are the relevant tickets?
close #1, first place baby
#### Screenshots (if appropriate)
I nominate if no screenshots are necessary that we require each other to include at least one non-sequitur gif 
slack-imgs
#### Questions:
* Do you like this PR template? 
* What's your favorite color shoe?

### CODE REVIEW

**Review by carlymclift — APPROVED** [review]
I approve this message.

And I got to go with black, black shoes always.

**Review by nickhartdev — APPROVED** [review]
I agree with all of this - and white shoes!

**Comment by GreysonElkins** [comment]
My favorite pair is a yellow suede chelsea boot
and @Abdeboskey, I know you watched me post this, but the `approval hot potato + merge` is to you
hot tato

**Review by Abdeboskey — APPROVED** [review]
Looks great, this is the template that I have used in the past and I like it. Any shoe with chartreuse accents.

**Pull request merged**
