### PR TITLE
Style/abd sass transition

### PR DESCRIPTION
**Pull request by Abdeboskey**
#### What's this PR do?
* Begin the transition of sass and styling
#### Where should the reviewer start?
* Start at Header.scss, and Instructions.scss
#### How should this be manually tested?
* With the eyes 👀
#### Any background context you want to provide?
* This is the beginning of a major style overhaul
#### What are the relevant tickets?
* #38 & #43 
#### Screenshots (if appropriate)
Screen Shot 2020-09-14 at 4 59 13 PM

#### Questions:
This is certainly just the beginning, but any thoughts or edits?

### CODE REVIEW

**Comment by GreysonElkins** [comment]
WOAH those pointers omg

**Review by carlymclift — APPROVED** [review]
Love the styling and fonts! Keep it comin!

**Review by nickhartdev — APPROVED** [review]
The styling looks so good! Seconding Greyson, the pointers are amazing

**Comment by GreysonElkins** [comment]
Just got the live walk-through on this with you and I wanna reiterate: _**DOPE**_

**Review by GreysonElkins — APPROVED** [review]

**Pull request merged**
